-- 기여 대상으로 등록된 외부 OSS 저장소.
--
-- 이 테이블이 가리키는 것은 대상 저장소이지 이 프로젝트 자신이 아니다.
-- ERD 전체(7테이블)는 .claude/codemaps/data.md 에 있고, 나머지는 #5 에서 만든다.
--
-- H2(MODE=PostgreSQL)와 PostgreSQL 양쪽에서 같은 SQL 이 돌아야 한다 — Q-2.
-- 벤더 고유 문법(JSONB · 파티셔닝 · TEXT 계열 차이)을 쓰지 않는다.

CREATE TABLE oss_repositories
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner           VARCHAR(255) NOT NULL,
    name            VARCHAR(255) NOT NULL,
    url             VARCHAR(255) NOT NULL,
    enabled         BOOLEAN      NOT NULL,
    last_scanned_at TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT uk_oss_repositories_url UNIQUE (url)
);

-- 스캔 대상 선별 — 활성 저장소를 오래된 순으로 고른다.
-- 스캐너가 매번 도는 질의라 인덱스가 없으면 등록 수에 비례해 느려진다.
CREATE INDEX idx_oss_repositories_enabled_last_scanned
    ON oss_repositories (enabled, last_scanned_at);
