-- 파이프라인 6테이블. PRD §22 ERD · .claude/codemaps/data.md 기준.
--
-- oss_repositories(V1) ──1:1──▶ repository_policy
--        │
--        └──1:N──▶ issue ──1:0..1──▶ contribution_candidate
--                                            ├──1:N──▶ agent_run
--                                            ├──1:N──▶ generated_change
--                                            └──1:0..1──▶ pull_request
--
-- 규율:
--  · H2(MODE=PostgreSQL)와 PostgreSQL 공통 문법만 쓴다 — Q-2 · Q-2b
--  · 참조는 경계를 기준으로 갈린다 (.claude/rules/conventions/architecture.md 규율 ④):
--      도메인 안  → JPA 연관관계 OK · 물리 FK OK        (repository_policy → oss_repository)
--      경계 넘음  → 값만 보관 · 물리 FK 없음 · 연관관계 없음
--
--    둘 다 없애는 이유가 다르다. 연관관계를 막는 것은 컴파일 결합 때문이고
--    (걸면 agent 가 candidate 의 엔티티를 import 하게 되어 떼어낼 때 코드를 고쳐야 한다),
--    물리 FK 를 막는 것은 테이블을 다른 DB 로 옮길 때 제약이 깨지고 삭제 순서가 DB 에
--    묶이기 때문이다. 대신 참조 무결성은 애플리케이션과 테스트가 책임진다
--  · UNIQUE 제약 4종이 멱등성의 근거다. 없으면 재실행이 중복을 만든다

-- ─────────────────────────────────────────────────────────────
-- 대상 저장소의 기여 규약. 없으면 구현 단계로 넘어가지 않는다 — S-5
-- ─────────────────────────────────────────────────────────────
CREATE TABLE repository_policy
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repository_id            BIGINT       NOT NULL,
    java_version             VARCHAR(255),
    build_command            VARCHAR(255),
    test_command             VARCHAR(255),
    issue_reference_required BOOLEAN      NOT NULL DEFAULT FALSE,
    signoff_required         BOOLEAN      NOT NULL DEFAULT FALSE,
    tests_required           BOOLEAN      NOT NULL DEFAULT FALSE,

    -- ⚠ NULL 을 허용하는 것이 핵심이다 — S-5.
    -- NULL = 판정 실패 = 보류(허용 아님). NOT NULL DEFAULT TRUE 로 두면
    -- 「AI 기여 금지」 저장소를 기본 허용해 버린다. 기본값이 곧 위반이 된다
    ai_contribution_allowed  BOOLEAN,

    contribution_rules       TEXT,                                  -- 대용량 · 스크럽 대상(S-4)
    analyzed_at              TIMESTAMP(6) WITH TIME ZONE,           -- 규약은 바뀐다. 재분석 주기 판단
    created_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT uk_repository_policy_repository UNIQUE (repository_id),
    CONSTRAINT fk_repository_policy_repository
        FOREIGN KEY (repository_id) REFERENCES oss_repositories (id)
);

-- ─────────────────────────────────────────────────────────────
-- 수집된 GitHub 이슈
-- ─────────────────────────────────────────────────────────────
CREATE TABLE issue
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- oss_repository.id 를 가리키는 논리 참조. 경계를 넘으므로 물리 FK 를 걸지 않는다
    repository_id       BIGINT       NOT NULL,
    github_issue_number INTEGER      NOT NULL,
    title               VARCHAR(1024),
    body                TEXT,                                       -- 대용량 · 목록 조회에서 제외
    state               VARCHAR(255) NOT NULL,
    url                 VARCHAR(512),
    labels              VARCHAR(1024),                              -- 필터 근거 (good first issue 등)

    -- 왜 배제됐는지 남긴다. 없으면 같은 이슈를 매 스캔마다 다시 판정한다
    filter_result       VARCHAR(255),
    filter_reason       TEXT,

    github_created_at   TIMESTAMP(6) WITH TIME ZONE,
    github_updated_at   TIMESTAMP(6) WITH TIME ZONE,                -- 증분 수집 커서
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    -- 멱등키 — 없으면 재스캔마다 같은 이슈가 중복 적재되고 후보도 중복 생성된다
    CONSTRAINT uk_issue_repository_number UNIQUE (repository_id, github_issue_number)
);

CREATE INDEX idx_issue_repository_updated ON issue (repository_id, github_updated_at);
CREATE INDEX idx_issue_state_filter ON issue (state, filter_result);

-- ─────────────────────────────────────────────────────────────
-- 기여 후보. 상태머신의 주체 — .claude/codemaps/domain.md
-- ─────────────────────────────────────────────────────────────
CREATE TABLE contribution_candidate
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id                BIGINT       NOT NULL,
    category                VARCHAR(255),
    difficulty              VARCHAR(255),
    estimated_files         INTEGER,
    estimated_loc           INTEGER,
    implementation_feasible BOOLEAN,
    breaking_change         BOOLEAN,
    confidence              NUMERIC(3, 2),                          -- 0.00 ~ 1.00
    analysis                TEXT,                                   -- 대용량 · 스크럽 대상(S-4)
    status                  VARCHAR(255) NOT NULL,                  -- CandidateStatus 11종

    -- ⚠ 사람이 고른 시각 — S-6. NULL 이면 구현 단계로 갈 수 없다.
    -- 「사람이 최종 승인한다」는 제품 정의의 유일한 데이터 증거다
    selected_at             TIMESTAMP(6) WITH TIME ZONE,

    created_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    -- 멱등키 — 이슈당 후보 1건. 둘 생기면 같은 작업을 두 번 하고 PR 도 두 개 난다
    CONSTRAINT uk_contribution_candidate_issue UNIQUE (issue_id)
);

CREATE INDEX idx_contribution_candidate_status ON contribution_candidate (status);

-- ─────────────────────────────────────────────────────────────
-- 파이프라인 한 단계의 1회 실행 기록. 비용·재시도의 유일한 근거
-- ─────────────────────────────────────────────────────────────
CREATE TABLE agent_run
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- contribution_candidate.id 를 가리키는 논리 참조. 경계를 넘으므로 물리 FK 를 걸지 않는다
    -- contribution_candidate.id 를 가리키는 논리 참조. 경계를 넘으므로 물리 FK 를 걸지 않는다
    -- contribution_candidate.id 를 가리키는 논리 참조. 경계를 넘으므로 물리 FK 를 걸지 않는다
    candidate_id  BIGINT       NOT NULL,
    stage         VARCHAR(255) NOT NULL,                            -- ANALYZE/PLAN/CODE/VERIFY/REVIEW

    -- ⚠ 의미가 아직 미정이다 — Q-6. 단계별 독립 카운터인지 후보 통합인지.
    -- 컬럼만 만들어 두고 해석은 #21 에서 확정한다
    attempt       INTEGER      NOT NULL,

    input_tokens  INTEGER,
    output_tokens INTEGER,
    status        VARCHAR(255) NOT NULL,                            -- RUNNING/SUCCEEDED/FAILED
    error_message TEXT,                                             -- 스크럽 대상(S-4) — 스택트레이스에 토큰이 섞인다
    started_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    finished_at   TIMESTAMP(6) WITH TIME ZONE

);

CREATE INDEX idx_agent_run_candidate_stage ON agent_run (candidate_id, stage, attempt);

-- ─────────────────────────────────────────────────────────────
-- AI 가 만든 변경분. 재시도마다 새 행을 남기고 덮어쓰지 않는다
-- ─────────────────────────────────────────────────────────────
CREATE TABLE generated_change
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id  BIGINT       NOT NULL,
    branch_name   VARCHAR(512),                                     -- oss-agent/issue-{n}-{slug}
    commit_sha    VARCHAR(64),
    diff          TEXT,                                             -- 가장 큰 컬럼 · 스크럽 대상(S-4)
    test_result   TEXT,                                             -- 대용량 · 스크럽 대상(S-4)
    review_result TEXT,                                             -- 대용량 · 스크럽 대상(S-4)
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL

);

CREATE INDEX idx_generated_change_candidate_created ON generated_change (candidate_id, created_at);

-- ─────────────────────────────────────────────────────────────
-- Draft PR 메타데이터. 자동화는 여기서 끝난다
-- ─────────────────────────────────────────────────────────────
CREATE TABLE pull_request
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- contribution_candidate.id 를 가리키는 논리 참조. 경계를 넘으므로 물리 FK 를 걸지 않는다
    -- contribution_candidate.id 를 가리키는 논리 참조. 경계를 넘으므로 물리 FK 를 걸지 않는다
    -- contribution_candidate.id 를 가리키는 논리 참조. 경계를 넘으므로 물리 FK 를 걸지 않는다
    candidate_id     BIGINT       NOT NULL,

    -- ⚠ push 대상 Fork 의 좌표 — S-1.
    -- 스키마에 upstream 좌표가 없다는 뜻이 아니다. oss_repositories.url 과 아래 pr_url 은
    -- upstream 을 가리킨다. S-1 의 방어는 컬럼 구성이 아니라 push 직전 owner 어설션이고,
    -- 그것은 #22 소관이다. 여기서는 「Fork 좌표를 반드시 남긴다」만 강제한다
    fork_url         VARCHAR(512) NOT NULL,

    branch_name      VARCHAR(512) NOT NULL,
    github_pr_number INTEGER,
    pr_url           VARCHAR(512),                                 -- upstream PR 주소 (생성 결과)

    -- ⚠ DRAFT 외의 값을 DB 가 거부한다 — S-2.
    -- DEFAULT 로 두면 방어가 되지 않는다. Hibernate 는 INSERT 에 모든 컬럼을 실어 보내므로
    -- DB DEFAULT 가 적용될 일이 없고, 어떤 값이든 그대로 들어간다. CHECK 여야 막힌다
    status           VARCHAR(255) NOT NULL,

    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    -- 멱등키 — 후보당 PR 1건. 없으면 재시도 시 대상 저장소에 PR 이 두 개 열린다.
    -- 남의 저장소에 중복 PR 을 여는 것은 스팸으로 취급된다 — S-2
    CONSTRAINT uk_pull_request_candidate UNIQUE (candidate_id),
    CONSTRAINT uk_pull_request_fork_branch UNIQUE (fork_url, branch_name),

    -- S-2 의 스키마 차원 방어. 코드가 실수로 다른 값을 넣어도 DB 가 거부한다.
    -- 「PR 은 항상 draft」는 이 제품의 존재 이유에 걸린 규칙이라 한 겹으로 두지 않는다
    CONSTRAINT ck_pull_request_status_draft CHECK (status = 'DRAFT')

);
